# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import policies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('carrier_name', models.CharField(max_length=100)),
                ('policy_number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('cust_serv_number', models.IntegerField(blank=True, null=True)),
                ('cust_serv_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frequency', models.CharField(blank=True, choices=[(b'monthly', b'monthly'), (b'weekly', b'weekly'), (b'quarterly', b'quarterly'), (b'annually', b'annually')], max_length=20, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to=policies.models.file_name)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together=set([('carrier_name', 'policy_number')]),
        ),
    ]
